version: '3.9'

services:
  kura-api:
    build: .
    container_name: kura_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=User Id=RM562999;Password=${ORACLE_PASSWORD};Data Source=oracle.fiap.com.br:1521/orcl
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=kura-api
      - Jwt__Audience=kura-client
      - IoT__ApiKey=${IOT_API_KEY}
      - Luna__ApiKey=${LUNA_API_KEY}
    restart: on-failure
