version: '3.9'

services:
  kura-api:
    build:
      context: .
      dockerfile: src/Kura.Api/Dockerfile
    container_name: kura_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=User Id=RM562999;Password=081105;Data Source=oracle.fiap.com.br:1521/orcl
      - Jwt__Key=kura-api-secret-key-fiap-2026-clyvovet
      - Jwt__Issuer=kura-api
      - Jwt__Audience=kura-client
      - IoT__ApiKey=kura-iot-device-key-2026
      - Luna__ApiKey=kura-luna-integration-key-2026
    restart: on-failure
