BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"INVITE_TUTOR" (
    "ID_INVITE_TUTOR" NUMBER(19) DEFAULT (SEQ_INVITE_TUTOR.NEXTVAL) NOT NULL,
    "ID_TUTOR" NUMBER(19) NOT NULL,
    "NR_TOKEN" RAW(16) NOT NULL,
    "DT_EXPIRACAO" TIMESTAMP(7) NOT NULL,
    "DS_CANAL" NVARCHAR2(20) NOT NULL,
    "ST_UTILIZADO" CHAR(1) NOT NULL,
    "ST_ATIVA" CHAR(1) NOT NULL,
    "DT_CRIACAO" TIMESTAMP(7) NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP(7),
    CONSTRAINT "PK_INVITE_TUTOR" PRIMARY KEY ("ID_INVITE_TUTOR"),
    CONSTRAINT "FK_INVITE_TUTOR_TUTOR_ID_TUTOR" FOREIGN KEY ("ID_TUTOR") REFERENCES "TUTOR" ("ID") ON DELETE CASCADE
)';
END;
/

CREATE INDEX "IX_INVITE_TUTOR_ID_TUTOR" ON "INVITE_TUTOR" ("ID_TUTOR")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260511125741_AddInviteTutor', N'10.0.7')
/

