// <auto-generated />
using System;
using Kura.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Kura.Infrastructure.Migrations
{
    [DbContext(typeof(KuraDbContext))]
    [Migration("20260808043056_Task67_InteracaoCanal")]
    partial class Task67_InteracaoCanal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kura.Domain.Entities.Agendamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_AGENDAMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DsMotivoCancel")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MOTIVO_CANCEL");

                    b.Property<string>("DsObservacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACOES");

                    b.Property<string>("DsOrigem")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_ORIGEM");

                    b.Property<string>("DsProvedorVideo")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("DS_PROVEDOR_VIDEO");

                    b.Property<string>("DsSalaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("DS_SALA_URL");

                    b.Property<string>("DsServico")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_SERVICO");

                    b.Property<string>("DsTipoConsulta")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("DS_TIPO");

                    b.Property<DateTime>("DtAgendamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_AGENDAMENTO");

                    b.Property<DateTime?>("DtCancelamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CANCELAMENTO");

                    b.Property<DateTime?>("DtConfirmacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CONFIRMACAO");

                    b.Property<DateTime?>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime?>("DtFimSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_FIM_SESSAO");

                    b.Property<DateTime?>("DtInicioSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIO_SESSAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long?>("IdEventoGerado")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_GERADO");

                    b.Property<long?>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<long?>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<long?>("IdVeterinario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("NmPaciente")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_PACIENTE");

                    b.Property<int?>("NrDuracaoMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_DURACAO_MINUTOS");

                    b.Property<long>("NrVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_VERSION");

                    b.Property<string>("StStatus")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ST_STATUS");

                    b.Property<string>("StTeleconsulta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_TELECONSULTA");

                    b.HasKey("Id");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdTutor");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("AGENDAMENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.AlertaTemperatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA")
                        .HasDefaultValueSql("SEQ_ALERTA_TEMP.NEXTVAL");

                    b.Property<string>("DsMensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("DsTipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_TIPO_ALERTA");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdLeituraTemperatura")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA_TEMPERATURA");

                    b.Property<string>("StResolvido")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_RESOLVIDO");

                    b.Property<decimal>("VlLimite")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_LIMITE");

                    b.HasKey("Id");

                    b.HasIndex("IdLeituraTemperatura");

                    b.ToTable("ALERTA_TEMPERATURA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Clinica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA")
                        .HasDefaultValueSql("SEQ_CLINICA.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsEmailAcesso")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DS_EMAIL_ACESSO");

                    b.Property<string>("DsEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("DsSenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DS_SENHA_HASH");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("NmCidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("NmClinica")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NM_CLINICA");

                    b.Property<string>("NmRazaoSocial")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_RAZAO_SOCIAL");

                    b.Property<string>("NrCep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR2(9)")
                        .HasColumnName("NR_CEP");

                    b.Property<string>("NrCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<string>("NrTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_TELEFONE");

                    b.Property<string>("SgUf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SG_UF");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("DsEmailAcesso")
                        .IsUnique();

                    b.HasIndex("NrCnpj")
                        .IsUnique();

                    b.ToTable("CLINICA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Consentimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CONSENTIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DsTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_TIPO");

                    b.Property<DateTime>("DtConsentimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ACEITE");

                    b.Property<long>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("NrVersaoTermo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_VERSAO_TERMO");

                    b.Property<string>("StAceito")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ACEITO");

                    b.HasKey("Id");

                    b.ToTable("CONSENTIMENTO", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Kura.Domain.Entities.Consulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CONSULTA")
                        .HasDefaultValueSql("SEQ_CONSULTA.NEXTVAL");

                    b.Property<string>("DsAnamnese")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ANAMNESE");

                    b.Property<string>("DsDiagnostico")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_DIAGNOSTICO");

                    b.Property<string>("DsExameFisico")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_EXAME_FISICO");

                    b.Property<string>("DsMotivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_MOTIVO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CONSULTA");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico")
                        .IsUnique();

                    b.ToTable("CONSULTA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.ContaTutor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CONTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_EMAIL_LOGIN");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("StEmailVerificado")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_EMAIL_VERIFICADO");

                    b.HasKey("Id");

                    b.HasIndex("IdTutor");

                    b.ToTable("CONTA_TUTOR", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Kura.Domain.Entities.DispositivoIot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO")
                        .HasDefaultValueSql("SEQ_DISPOSITIVO_IOT.NEXTVAL");

                    b.Property<string>("CdDispositivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CD_DISPOSITIVO");

                    b.Property<string>("DsDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("DsLocalizacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.HasKey("Id");

                    b.HasIndex("CdDispositivo")
                        .IsUnique();

                    b.HasIndex("IdClinica");

                    b.ToTable("DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DOCUMENTO")
                        .HasDefaultValueSql("SEQ_DOCUMENTO.NEXTVAL");

                    b.Property<string>("DsCaminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_CAMINHO");

                    b.Property<string>("DsTipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_TIPO_MIME");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("NmArquivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_ARQUIVO");

                    b.Property<long>("NrTamanhoBytes")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_TAMANHO_BYTES");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.ToTable("DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Especie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ESPECIE")
                        .HasDefaultValueSql("SEQ_ESPECIE.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmEspecie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_ESPECIE");

                    b.HasKey("Id");

                    b.ToTable("ESPECIE", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.EventoClinico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO")
                        .HasDefaultValueSql("SEQ_EVENTO_CLINICO.NEXTVAL");

                    b.Property<string>("DsObservacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<string>("DsSoapA")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_SOAP_A");

                    b.Property<string>("DsSoapO")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_SOAP_O");

                    b.Property<string>("DsSoapP")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_SOAP_P");

                    b.Property<string>("DsSoapS")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_SOAP_S");

                    b.Property<string>("DsTranscricao")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_TRANSCRICAO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EVENTO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<long>("IdTipoEvento")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO_EVENTO");

                    b.Property<long>("IdVeterinario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("StSoapConfirmado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_SOAP_CONFIRMADO");

                    b.HasKey("Id");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdTipoEvento");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("EVENTO_CLINICO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Exame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EXAME")
                        .HasDefaultValueSql("SEQ_EXAME.NEXTVAL");

                    b.Property<string>("DsResultado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_RESULTADO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtRealizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REALIZACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("NmExame")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_EXAME");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.ToTable("EXAME", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.InteracaoCanal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_INTERACAO")
                        .HasDefaultValueSql("SEQ_INTERACAO_CANAL.NEXTVAL");

                    b.Property<string>("DsCanal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("DS_CANAL");

                    b.Property<string>("DsConteudo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("DS_CONTEUDO");

                    b.Property<string>("DsDirecao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("DS_DIRECAO");

                    b.Property<string>("DsMetadados")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_METADADOS");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtRecebimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_RECEBIMENTO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long?>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.HasKey("Id");

                    b.ToTable("INTERACAO_CANAL", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.InviteTutor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_INVITE")
                        .HasDefaultValueSql("SEQ_INVITE_TUTOR.NEXTVAL");

                    b.Property<string>("DsCanal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_CANAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtExpiracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EXPIRACAO");

                    b.Property<long>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("NrToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("NR_TOKEN");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("StUtilizado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_UTILIZADO");

                    b.HasKey("Id");

                    b.HasIndex("IdTutor");

                    b.ToTable("INVITE_TUTOR", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.LeituraTemperatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA")
                        .HasDefaultValueSql("SEQ_LEITURA_TEMP.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<long>("IdDispositivoIot")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO_IOT");

                    b.Property<decimal>("VlTemperatura")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_TEMPERATURA");

                    b.Property<decimal?>("VlUmidade")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_UMIDADE");

                    b.HasKey("Id");

                    b.HasIndex("IdDispositivoIot");

                    b.ToTable("LEITURA_TEMPERATURA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Medicamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MEDICAMENTO")
                        .HasDefaultValueSql("SEQ_MEDICAMENTO.NEXTVAL");

                    b.Property<string>("DsApresentacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_APRESENTACAO");

                    b.Property<string>("DsPrincipioAtivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_PRINCIPIO_ATIVO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmMedicamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_MEDICAMENTO");

                    b.HasKey("Id");

                    b.ToTable("MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NOTIFICACAO")
                        .HasDefaultValueSql("SEQ_NOTIFICACAO.NEXTVAL");

                    b.Property<string>("DsMensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("DsTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_TITULO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime?>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long?>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<long?>("IdVeterinario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("StLida")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_LIDA");

                    b.HasKey("Id");

                    b.HasIndex("IdTutor");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET")
                        .HasDefaultValueSql("SEQ_PET.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long>("IdEspecie")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ESPECIE");

                    b.Property<long>("IdRaca")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RACA");

                    b.Property<long?>("IdVeterinarioResp")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO_RESP");

                    b.Property<string>("NmPet")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_PET");

                    b.Property<string>("SgPorte")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("SG_PORTE");

                    b.Property<string>("SgSexo")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("SG_SEXO");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdRaca");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Prescricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PRESCRICAO")
                        .HasDefaultValueSql("SEQ_PRESCRICAO.NEXTVAL");

                    b.Property<string>("DsPosologia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_POSOLOGIA");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<long>("IdMedicamento")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MEDICAMENTO");

                    b.Property<int>("NrDuracaoDias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_DURACAO_DIAS");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.HasIndex("IdMedicamento");

                    b.ToTable("PRESCRICAO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Raca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RACA")
                        .HasDefaultValueSql("SEQ_RACA.NEXTVAL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdEspecie")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ESPECIE");

                    b.Property<string>("NmRaca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_RACA");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.ToTable("RACA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.TipoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO_EVENTO")
                        .HasDefaultValueSql("SEQ_TIPO_EVENTO.NEXTVAL");

                    b.Property<string>("CdTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CD_TIPO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_TIPO");

                    b.HasKey("Id");

                    b.HasIndex("CdTipo")
                        .IsUnique();

                    b.ToTable("TIPO_EVENTO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.TriagemLuna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TRIAGEM")
                        .HasDefaultValueSql("SEQ_TRIAGEM_LUNA.NEXTVAL");

                    b.Property<string>("DsDescricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("DsNivelUrgencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_NIVEL_URGENCIA");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtTriagem")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_TRIAGEM");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<long?>("IdInteracao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_INTERACAO");

                    b.Property<long?>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<long?>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVA");

                    b.Property<string>("StEncaminhadoVet")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ENCAMINHADO_VET");

                    b.HasKey("Id");

                    b.ToTable("TRIAGEM_LUNA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Tutor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR")
                        .HasDefaultValueSql("SEQ_TUTOR.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsVersaoAviso")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_VERSAO_AVISO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime?>("DtAvisoPrivacidade")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_AVISO_PRIVACIDADE");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("NmTutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_TUTOR");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_TELEFONE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("StAvisoPrivacidade")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_AVISO_PRIVACIDADE");

                    b.HasKey("Id");

                    b.HasIndex("NrCpf")
                        .IsUnique();

                    b.ToTable("TUTOR", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.TutorPet", b =>
                {
                    b.Property<long>("IdTutor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<long>("IdPet")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("DsVinculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_VINCULO");

                    b.Property<DateTime>("DtVinculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_VINCULO");

                    b.Property<string>("StPrincipal")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_PRINCIPAL");

                    b.HasKey("IdTutor", "IdPet");

                    b.HasIndex("IdPet");

                    b.ToTable("TUTOR_PET", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Vacina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VACINA")
                        .HasDefaultValueSql("SEQ_VACINA.NEXTVAL");

                    b.Property<string>("DsFabricante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_FABRICANTE");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime?>("DtProximaDose")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PROXIMA_DOSE");

                    b.Property<long>("IdEventoClinico")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_CLINICO");

                    b.Property<string>("NmVacina")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_VACINA");

                    b.Property<string>("NrLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NR_LOTE");

                    b.HasKey("Id");

                    b.HasIndex("IdEventoClinico");

                    b.ToTable("VACINA", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Veterinario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VETERINARIO")
                        .HasDefaultValueSql("SEQ_VETERINARIO.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdClinica")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("NmVeterinario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_VETERINARIO");

                    b.Property<string>("NrCrmv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_CRMV");

                    b.Property<string>("NrTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("StAtiva")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex("IdClinica");

                    b.HasIndex("NrCrmv")
                        .IsUnique();

                    b.ToTable("VETERINARIO", (string)null);
                });

            modelBuilder.Entity("Kura.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("IdPet");

                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("IdTutor");

                    b.HasOne("Kura.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("IdVeterinario");

                    b.Navigation("Pet");

                    b.Navigation("Tutor");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Kura.Domain.Entities.AlertaTemperatura", b =>
                {
                    b.HasOne("Kura.Domain.Entities.LeituraTemperatura", "LeituraTemperatura")
                        .WithMany()
                        .HasForeignKey("IdLeituraTemperatura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeituraTemperatura");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.ContaTutor", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Kura.Domain.Entities.DispositivoIot", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.EventoClinico", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.TipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("IdTipoEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("TipoEvento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Exame", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.InviteTutor", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Invites")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Kura.Domain.Entities.LeituraTemperatura", b =>
                {
                    b.HasOne("Kura.Domain.Entities.DispositivoIot", "DispositivoIot")
                        .WithMany("Leituras")
                        .HasForeignKey("IdDispositivoIot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispositivoIot");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kura.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tutor");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Pet", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Raca", "Raca")
                        .WithMany()
                        .HasForeignKey("IdRaca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Prescricao", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Raca", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Kura.Domain.Entities.TutorPet", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Pet", "Pet")
                        .WithMany("TutorPets")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kura.Domain.Entities.Tutor", "Tutor")
                        .WithMany("TutorPets")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Vacina", b =>
                {
                    b.HasOne("Kura.Domain.Entities.EventoClinico", "EventoClinico")
                        .WithMany()
                        .HasForeignKey("IdEventoClinico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoClinico");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Veterinario", b =>
                {
                    b.HasOne("Kura.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("Kura.Domain.Entities.DispositivoIot", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Especie", b =>
                {
                    b.Navigation("Racas");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Pet", b =>
                {
                    b.Navigation("TutorPets");
                });

            modelBuilder.Entity("Kura.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("TutorPets");
                });
#pragma warning restore 612, 618
        }
    }
}
