using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kura.Infrastructure.Migrations
{
    // Evidência FIAP — nunca aplicada em produção (Flyway é a autoridade de DDL, ver CLAUDE.md).
    // TASK-25 (DB-01), Caminho A: o Flyway do repo Java ganhou a migration
    // V12__sequences_dotnet.sql, que cria as 20 sequences (SEQ_CLINICA, SEQ_ESPECIE, ...)
    // que as *Configuration.cs deste projeto já esperavam via HasDefaultValueSql("SEQ_x.NEXTVAL")
    // desde antes desta task — e converte as PKs correspondentes de
    // GENERATED BY DEFAULT AS IDENTITY para DEFAULT SEQ_x.NEXTVAL, eliminando o ORA-02289
    // que ocorria em qualquer ambiente que não fosse bootstrapado por
    // DevOps-Cloud/db/init/01_schema.sql. Zero mudança de código no .NET: nenhuma
    // *Configuration.cs foi alterada por esta task, por isso Up()/Down() não têm operações —
    // o `dotnet ef migrations add` não detectou drift de modelo porque não havia nenhum.
    // Esta migration vazia é a prova de que o .NET já estava alinhado com o schema que a
    // V12 cria; ver docs/V12-pk-strategy-map.md (repo backend-tutor-java) para o mapa
    // completo das 20 tabelas convertidas.
    /// <inheritdoc />
    public partial class AddV12DotnetSequences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
